### PR TITLE
feat: upgrade for node20

### PR DESCRIPTION
**Pull request by tisonkun**
GitHub deprecates node16. Let's upgrade to node20.

Hopefully we can have a release with this patch also.

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @dacbd

**Comment by dacbd** [comment]
@tisonkun Thanks! This was on my todo list, I'll merge today and create some new tags.

**Comment by dacbd** [comment]
@tisonkun release has been published as well as new tracking tags `v2`, `v2.0`, and `v2.0.0`.

**Comment by tisonkun** [comment]
Cool! Thank you :D

**Pull request merged**
